const express  = require('express');
//const auth = require('../controllers/userCtrl');
const router = express.Router();
//const languageDetection = require('../middlewares/languageDetection');
//const {authMiddleware, isAdmin} = require("../middlewares/authMiddleware");
//router.use(languageDetection);

// router.post("/register",auth.createUser);
// router.post("/login",auth.loginUserCtrl);
// router.post("/logout", auth.logoutUserCtrl);
// router.get("/all-users",auth.getAllUsers);
// router.get("/all-admins",auth.getAllAdminUsers);
// router.get("/get-user/:id",authMiddleware,auth.getUser);
// router.delete("/delete-user/:id",auth.deleteUser);
// router.put("/update-user/:id",authMiddleware,auth.updateUser);
// router.put("/update-admin/:id",auth.updateUserAdmin);
// router.post("/login-admin",isAdmin,auth.loginAdminCtrl);
// router.post("/verify", auth.verifyOTP);
// router.post("/resendOTP",auth.resendOTP);
// router.post("/add-to-wish",authMiddleware,auth.addToWish);
// router.get("/get-whish/:id",authMiddleware,auth.getUserWishlist);
// router.delete("/delete-whish",authMiddleware,auth.removeFromWishlist);
// router.post("/add-to-cart",authMiddleware,auth.addToCart);
// router.put("/update-cart",authMiddleware,auth.updateCartQuantity);
// router.get("/getCart/:id",authMiddleware,auth.getUserCart);
// router.delete("/delete-item-cart",authMiddleware,auth.removeFromCart);
module.exports = router;